- name: Redis Playbook
  hosts: Redis
  become: yes
  tasks:
  - name: Install remi
    ansible.builtin.dnf: #dnf or package
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      #disable_gpg_check: true

  - name: Enable redis
    ansible.builtin.command: module enable redis:remi-6.2

  - name: Install Redis
    ansible.builtin.package: 
      name: redis
      state: present

  - name: Allow remote connections 
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: Start and Enable redis
    anisible.builtin.service:
      name: redis
      state: started 
      enabled: yes
